In [12]:
import numpy as np
import pandas as pd
import math
from sklearn import linear_model

In [3]:
data={'area':[2600,3000,3200,3600,4000],'bedrooms':[3,4,None,3,5],'age':[20,15,18,30,8],'price':[550000,565000,610000,595000,760000]}

In [4]:
df=pd.DataFrame(data)

### Data Preprocessing

In [5]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
df.describe()

area  bedrooms       age          price
count     5.000000  4.000000   5.00000       5.000000
mean   3280.000000  3.750000  18.20000  616000.000000
std     540.370243  0.957427   8.01249   83919.604384
min    2600.000000  3.000000   8.00000  550000.000000
25%    3000.000000  3.000000  15.00000  565000.000000
50%    3200.000000  3.500000  18.00000  595000.000000
75%    3600.000000  4.250000  20.00000  610000.000000
max    4000.000000  5.000000  30.00000  760000.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   area      5 non-null      int64  
 1   bedrooms  4 non-null      float64
 2   age       5 non-null      int64  
 3   price     5 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 292.0 bytes


In [10]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

We need to handle this one missing value in bedrooms column, to do that we will replace the missing value with median of the bedrooms column

In [15]:
df['bedrooms'].fillna(math.floor((df['bedrooms'].median())),inplace=True)

In [16]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [17]:
reg=linear_model.LinearRegression()

In [18]:
reg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression()

In [19]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [20]:
reg.intercept_

383724.9999999998

In [22]:
reg.predict([[3000,3,40]])

C:\Users\Prathamesh Patil\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [23]:
#testing
137.25*3000+(-26025*3)+(-6825*40)+383724.9999999998


444399.9999999998

In [30]:
reg.predict([[2500,4,5]])

C:\Users\Prathamesh Patil\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])